version: '3'
services:
  db:
    container_name: 'mud-db'
    image: postgres
    environment:
      POSTGRES_USER: mudDB
      POSTGRES_PASSWORD: pgSecret
    ports:
      - 5412:5432
    networks:
      - dev_env_mud
  Portal:
    build: .
    container_name: 'mud-portal'
    image: 'laravel-alpine:latest'
    volumes:
      - './ezimeeting:/var/www/html/packages/mudtec/ezimeeting'
    ports:
      - "9010:80"
    depends_on:
      - db 
    networks:
      - dev_env_mud 
  admin:
    container_name: 'mud-admin'
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: stevewe@me.com
      PGADMIN_DEFAULT_PASSWORD: pgSecret
    ports:
      - 9011:80
    networks:
      - dev_env_mud
  mailhog:
    container_name: 'mud-mailhog'
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - dev_env_mud
networks:
  dev_env_mud:
    external: true   
