version: '3.8'
services:
  app:
    build: .
    container_name: 'laravel_app'
    restart: unless-stopped
    volumes:
      - '.:/var/www/html'
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:randomKeyHere
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: secret
    command: php artisan serve --host=0.0.0.0 --port=8000
 
  postgres:
    image: postgres:15
    container_name: 'postgres_db'
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    container_name: 'db-admin'
    environment:
      PGADMIN_DEFAULT_EMAIL: stevewe@me.com
      PGADMIN_DEFAULT_PASSWORD: pgSecret
    ports:
      - 8010:80

  mailhog:
    image: mailhog/mailhog:latest
    container_name: 'app-mailhog'
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  pgdata:
